/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_com_endava_facerecognition_FaceRecognitionProxy
#define _Included_com_endava_facerecognition_FaceRecognitionProxy
#ifdef __cplusplus
extern "C" {
#endif

//FaceDetectionProxy bindings
JNIEXPORT void JNICALL Java_com_endava_recognitionlibrary_FaceProcessingProxy_processImageAndDetectFaces(
		JNIEnv * jenv, jclass, jstring, jstring, jlong, jint);

JNIEXPORT bool JNICALL Java_com_endava_recognitionlibrary_FaceProcessingProxy_nativeCropFace(
		JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint);

//FaceRecognitionProxy bindings
JNIEXPORT jlong JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_createRecognizer(
		JNIEnv *, jclass, jstring, jint recognitionModelOrdinal);

JNIEXPORT jlong JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_createRecognizerWithCascade(
		JNIEnv *, jclass, jstring, jstring, jint recognitionModelOrdinal);

JNIEXPORT void JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_releaseRecognizer(
		JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_createModel(
		JNIEnv *, jclass, jlong, jstring, jobjectArray, jintArray);

JNIEXPORT jboolean JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_predictFace(
		JNIEnv *, jclass, jlong, jstring, jstring, jint, jdouble);

JNIEXPORT void JNICALL Java_com_endava_recognitionlibrary_FaceRecognitionProxy_updateModel(
		JNIEnv *, jclass, jlong, jstring, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
